// Shared type-generation logic used by both scripts/generate-types.mjs (the
// CLI/CI entry point) and test/generated-types.test.mjs (the drift check).

import { compile } from "json-schema-to-typescript";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { repoRoot } from "./pin.mjs";

export const docsDir = path.join(repoRoot, "docs");
export const outDir = path.join(repoRoot, "contract", "generated");

export const targets = [
  {
    schemaFile: "dashboard-projection-v1.schema.json",
    rootTypeName: "DashboardProjectionV1",
    outFile: "dashboard-projection-v1.ts",
  },
  {
    schemaFile: "agent-handoff-v1.schema.json",
    rootTypeName: "AgentHandoffV1",
    outFile: "agent-handoff-v1.ts",
  },
];

export function banner(schemaFile) {
  return `/* eslint-disable */
/**
 * This file was automatically generated from the pinned canonical schema
 * ${schemaFile} (see contract/pin.json for the exact Sensei source commit
 * and digest). Do not edit this file directly — run
 * \`npm run generate:types\` to regenerate it, and do not hand-add fields,
 * loosen required-ness, or otherwise diverge from what the schema declares.
 */

`;
}

/** Returns { outFile, contents } for every target, without writing anything. */
export async function generateAll() {
  const results = [];
  for (const target of targets) {
    const schemaPath = path.join(docsDir, target.schemaFile);
    const schema = JSON.parse(await readFile(schemaPath, "utf8"));

    const ts = await compile(schema, target.rootTypeName, {
      cwd: docsDir,
      bannerComment: "",
      declareExternallyReferenced: true,
      enableConstEnums: true,
      style: { singleQuote: false },
      additionalProperties: false,
      unreachableDefinitions: true,
      $refOptions: { resolve: { http: false } },
    });

    results.push({ outFile: target.outFile, contents: banner(target.schemaFile) + ts });
  }
  return results;
}
